[package]
name = "buoyfinder"
version = "0.1.0"
authors = ["Matthew Iannucci <mpiannucci@gmail.com>"]

[lib]
name = "buoyfinder"
crate-type = ["staticlib"]

[dependencies]
libc = "*"
serde = "1.0"
serde_derive = "1.0"
serde-xml-rs = "0.2.1"

[build-dependencies]
cbindgen = "*"
