[package]
name = "buoyfinder-cli"
version = "0.1.0"
authors = ["Matthew Iannucci <mpiannucci@gmail.com>"]
edition = "2018"

[dependencies]
buoyfinder_core = { path = "../core" }
reqwest = { version = "0.10", features = ["blocking"] }