use_frameworks!

target 'BuoyFinder' do
    platform :ios, 10.1

    pod 'GoogleMaps'
    pod 'GooglePlaces'
    pod 'SwiftLocation'
    pod 'AsyncImageView'
    pod 'Pulley'

    pod 'RxSwift',    '~> 4.0'
    pod 'RxCocoa',    '~> 4.0'
end
